server:
  port: 8080
spring:
  data:
    mongodb:
      host: localhost
      authentication-database: admin
      database: test
      username: root
      password: 123456
      port: 27017
  application:
    name: tps
